apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  template:
    spec:
      containers:
      - name: mosquitto
        volumeMounts:
          - name: password-file
            mountPath: /mosquitto/config/password_file.txt
            subPath: password_file.txt
          - name: mosquitto-data
            mountPath: /mosquitto/data
      volumes:
        - name: password-file
          secret:
            secretName: mosquitto-password     
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-pvc
