apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  template:
    spec:
      containers:
      - name: mosquitto
        volumeMounts:
          - name: mosquitto-data
            mountPath: /mosquitto/data
      volumes:
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-pvc
