apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- pvc.yml
- sealedsecret.yml
patchesStrategicMerge:
- configmap-patch.yml
- service-patch.yml
- deployment-patch.yml
