kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-pvc
  namespace: mqtt
  labels:
    app: mosquitto
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
